version: '3.2' 

services:
  web:
    image: pesugihan_online:latest
    ports:
      - "10001:8080"
    networks:
      - pesugihan_network
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]

networks:
  pesugihan_network:
    driver: overlay
    attachable: true
